# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://bbbgan.github.io/
date_format: "ordinal"
title: bbbGan
subtitle: "waiting for fill"
description: "bbbgan's personal blog"

encoding: "utf-8"
# 页面左下角显示的年份
since: 2022
# 源码仓库，请替换成自己的
repository: bbbgan/bbbgan.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    word_count:
        enabled: true
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
    # 图片灯箱效果功能
    fancybox:
        enabled: false
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: bbbgan
organization: 
organization_url: 
github_username: bbbgan
location: Chengdu, China
email: ganjinbbo@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

#   -
#     href: /wiki/
#     label: 维基

#   -
#     href: /links/
#     label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus


# ---------------- #
#      Search      #
# ---------------- #
# simple_jekyll_search:
#     # 是否支持全文搜索
#     fulltext: false
#     # 最多显示多少条搜索结果
#     limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        sidebar-detail: true 
        content_header: false
        content_footer: false
